import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AdminHeader from "./admin-header";
import SideBar from "./side-bar";
// import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin Dashboard | Dashboard CRUD",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="admin-wrapper min-h-screen w-full flex flex-row">
      <SideBar />
      <div className="flex-4">
        <AdminHeader />
        <div className="p-10">{children}</div>
      </div>
    </div>
  );
}
